name: build-aes_cipher-openlane-sky130
on:
  push:
    branches:
      - main
    paths:
      - 'aes_cipher/**'
      - '.github/workflows/aes_cipher.yml'
jobs:
  build-openlane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout examples
        uses: actions/checkout@v2
      - name: Build with Openlane
        uses: librecores/ci-fusesoc-action@v1
        with:
          core: aes_cipher
          target: sky130
          tool: openlane
