name: build-aes_core-openlane-sky130
on:
  push:
    branches:
      - main
    paths:
      - 'aes_core/**'
jobs:
  build-openlane:
    runs-on: ubuntu-latest
    env:
      OPENLANE_ROOT: not_really_used
    steps:
      - name: Checkout examples
        uses: actions/checkout@v2
        with:
          path: openlane-examples
      - name: Checkout pdk
        uses: actions/checkout@v2
        with:
          repository: olofk/pdklite
          path: pdklite
      - run: echo "PDK_ROOT=$GITHUB_WORKSPACE/pdklite" >> $GITHUB_ENV
      - run: echo "EDALIZE_LAUNCHER=${GITHUB_WORKSPACE}/openlane-examples/openlane_runner.py" >> $GITHUB_ENV
      - run: pip3 install --user -e "git+https://github.com/olofk/edalize.git@master#egg=edalize"
      - run: pip3 install fusesoc
      - run: docker pull efabless/openlane:v0.12
      - run: fusesoc library add aes_core $GITHUB_WORKSPACE/openlane-examples/aes_core
      - run: fusesoc run --target=sky130 aes_core
      