name: build-blabla-openlane-sky130
on:
  push:
    branches:
      - main
    paths:
      - 'blabla/**'
      - '.github/workflows/blabla.yml'
jobs:
  build-openlane:
    runs-on: ubuntu-latest
    env:
      OPENLANE_ROOT: not_really_used
    steps:
      - name: Checkout examples
        uses: actions/checkout@v2
      - name: Build with Openlane
        uses: librecores/ci-fusesoc-action@v1
        with:
          core: blabla
          target: sky130
          tool: openlane
