name: build-genericfir-openlane-sky130
on:
  push:
    branches:
      - main
    paths:
      - 'genericfir/**'
      - '.github/workflows/genericfir.yml'
jobs:
  build-openlane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout examples
        uses: actions/checkout@v2
        with:
          path: openlane-examples
      - name: Checkout pdk
        uses: actions/checkout@v2
      - name: Build with Openlane
        uses: librecores/ci-fusesoc-action@v1
        with:
          core: genericfir
          target: sky130
          tool: openlane
