name: build-inverter-openlane-sky130
on:
  push:
    branches:
      - main
    paths:
      - 'inverter/**'
      - '.github/workflows/inverter.yml'
jobs:
  build-openlane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout examples
        uses: actions/checkout@v2
      - name: Build with Openlane
        uses: librecores/ci-fusesoc-action@v1
        with:
          core: inverter
          target: sky130
          tool: openlane
