name: build-ldpc_decoder_802_3an-openlane-sky130
on:
  push:
    branches:
      - main
    paths:
      - 'ldpc_decoder_802_3an/**'
      - '.github/workflows/ldpc_decoder_802_3an.yml'
jobs:
  build-openlane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout examples
        uses: actions/checkout@v2
      - name: Build with Openlane
        uses: librecores/ci-fusesoc-action@v1
        with:
          core: ldpc_decoder_802_3an
          target: sky130
          tool: openlane
