name: build-md5-openlane-sky130
on:
  push:
    branches:
      - main
    paths:
      - 'md5/**'
      - '.github/workflows/md5.yml'
jobs:
  build-openlane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout examples
        uses: actions/checkout@v2
      - name: Build with Openlane
        uses: librecores/ci-fusesoc-action@v1
        with:
          core: md5
          target: sky130
          tool: openlane
