name: build-picorv32a-openlane-sky130
on:
  push:
    branches:
      - main
    paths:
      - 'picorv32a/**'
      - '.github/workflows/picorv32a.yml'
jobs:
  build-openlane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout examples
        uses: actions/checkout@v2
      - name: Build with Openlane
        uses: librecores/ci-fusesoc-action@v1
        with:
          core: picorv32a
          target: sky130
          tool: openlane
