name: build-salsa20-openlane-sky130
on:
  push:
    branches:
      - main
    paths:
      - 'salsa20/**'
      - '.github/workflows/salsa20.yml'
jobs:
  build-openlane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout examples
        uses: actions/checkout@v2
      - name: Build with Openlane
        uses: librecores/ci-fusesoc-action@v1
        with:
          core: salsa20
          target: sky130
          tool: openlane
