name: build-synth_ram-openlane-sky130
on:
  push:
    branches:
      - main
    paths:
      - 'synth_ram/**'
      - '.github/workflows/synth_ram.yml'
jobs:
  build-openlane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout examples
        uses: actions/checkout@v2
      - name: Build with Openlane
        uses: librecores/ci-fusesoc-action@v1
        with:
          core: synth_ram
          target: sky130
          tool: openlane
