name: build-usb_cdc_core-openlane-sky130
on:
  push:
    branches:
      - main
    paths:
      - 'usb_cdc_core/**'
      - '.github/workflows/usb_cdc_core.yml'
jobs:
  build-openlane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout examples
        uses: actions/checkout@v2
      - name: Build with Openlane
        uses: librecores/ci-fusesoc-action@v1
        with:
          core: usb_cdc_core
          target: sky130
          tool: openlane
